# Generated by Django 4.2.5 on 2023-09-30 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Counter',
        ),
        migrations.DeleteModel(
            name='CounterSection',
        ),
    ]
