# Generated by Django 4.2.5 on 2023-10-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pro_detail',
            name='company_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
