# Generated by Django 4.2.5 on 2023-10-04 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countersection',
            name='counter_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
