# Generated by Django 4.2.5 on 2023-09-30 11:55

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_countersection_counter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_img', models.ImageField(upload_to='service')),
                ('service_name', models.CharField(max_length=150)),
                ('service_desc', ckeditor.fields.RichTextField()),
                ('created_at', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
