# Generated by Django 4.2.5 on 2023-09-30 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_type',
            field=models.CharField(choices=[('mobile_dev', 'Mobile Development'), ('web_dev', 'Web Development'), ('cms', 'Content Management Systems'), ('responsive_design', 'Responsive Web Design'), ('ui_ux', 'UI/UX-Driven Development'), ('cross_platform', 'Cross-Platform Solutions'), ('e-commerce_solutions', 'E-commerce Solutions')], default='web_dev', max_length=50),
        ),
    ]
