# Generated by Django 4.2.5 on 2023-09-30 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_service_service_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_img',
        ),
    ]
